# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# Copyright (c) MQSS Maintainers

services:
  # RabbitMQ broker.
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    ports:
      - "5672:5672"
      - "15672:15672"

  # Development container.
  workflow:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    image: mqss-dev
    depends_on:
      - rabbitmq
    working_dir: /workspace
    volumes:
      - ../..:/workspace

    # Make RabbitMQ reachable as "rabbitmq".
    environment:
      QRM_AMQP_HOST: rabbitmq
      QOFFLOAD_AMQP_HOST: rabbitmq

    stdin_open: true
    tty: true
    command: /bin/bash
